INSERT INTO public.menu_items (id, name, description, price, category, ingredients, calories, "sensoryNotes", "isPopular") VALUES
('w-1', 'Glenfiddich 18 Year', 'Honeyed oak with warming spice, dried fruit complexity and a long, smooth finish.', 85, 'whisky', ARRAY['Peated Malt', 'Charred Oak Cask', 'Spring Water'], 120, 'A pristine balance of slow-aged honey, dry cinnamon spice, and sherry wood undertones.', true),
('w-2', 'The Macallan 12', 'Rich dried fruits, vanilla, ginger, and wood spice with a sherry oak finish.', 92, 'whisky', ARRAY['Malted Barley', 'Sherry Seasoned Oak Casks', 'Natural Yeast'], 110, 'Deep amber fruitiness accompanied by toasted hazelnuts and a lingering sweet ginger prickle.', false),
('w-3', 'Hibiki Japanese Harmony', 'Honey, orange peel, white chocolate, and rose — a floral, silken pour.', 110, 'whisky', ARRAY['Malt & Grain Blends', 'Mizunara Oak Casks', 'Yamazaki Spring Water'], 115, 'Enthralling and delicate rosewood aromatics with a luxurious milk-chocolate finish.', true),
('w-4', 'Lagavulin 16', 'Dense peat smoke, iodine, and dark chocolate over a powerful, peaty body.', 98, 'whisky', ARRAY['Peated Islay Malt', 'Refill Oak Hogsheads', 'Moorland Water'], 125, 'Heavily smoky, iodine-rich salty sea spray, with sweet caramel molasses providing an anchor.', true),
('w-5', 'Amrut Fusion', 'Tropical fruits, malt, and a hint of smoke from Indian peated barley.', 62, 'whisky', ARRAY['Indian Unpeated Barley', 'Scottish Peated Barley', 'Himalayan Spring Runoff'], 118, 'Vibrant, thick mango custard, heavy fresh grain, with a surprising gentle peat smoke trail.', false),
('w-6', 'Redbreast 12', 'Orchard fruits, toasted wood, and warming spices — the quintessential Irish whiskey.', 75, 'whisky', ARRAY['Malted and Unmalted Barley', 'Bourbon and Sherry Casks', 'Midleton Spring Water'], 112, 'Beautifully round, creamy pot-still texture showing sweet baked apples and a deep walnut spice.', false),
('c-1', 'The Prohibition Sour', 'Our opening act. Smooth, frothy, with just enough citrus to wake you up before the night really begins.', 48, 'cocktail', ARRAY['High-Proof Bourbon', 'Fresh Lemon Juice', 'Organic Honey', 'Fresh Egg White', 'Angostura Bitters'], 180, 'Decadent, velvety foam followed by a tart, bracing lemon honey snap.', true),
('c-2', 'Smoky Old Fashioned', 'Peated Scotch, Demerara sugar, and hand-pressed cherry bitters, smoked tableside in a cedar chamber.', 52, 'cocktail', ARRAY['Peated Scotch', 'Aged Rye', 'Demerara Reduction', 'Cherry Bitters', 'Cedar Wood Smoke'], 190, 'Intense woodfire nose opening up to deep charred sugar and a sharp cherry bite.', false),
('c-3', 'The Peaky Mule', 'Rye whiskey, house-brewed ginger beer, and a heavy dash of spiced bitters.', 46, 'cocktail', ARRAY['Rye Whiskey', 'Macerated Ginger Brew', 'Lime Zest Oil', 'Spiced Bitters'], 165, 'Strong, highly carbonated ginger root kick offset by dry rye grain pepperiness.', false),
('k-1', 'The Temperate Old Fashioned', 'Distilled non-alcoholic dark wood spirit, smoked caramel, orange zest, and alcohol-free bitters.', 38, 'mocktail', ARRAY['Lyre’s American Malt', 'Smoked Demerara Syrup', 'Angostura-free Bitters', 'Orange Peel'], 60, 'Woody, warm and rich without the fire of alcohol, accompanied by crisp citrus oils.', false),
('k-2', 'Ginger Elixir', 'Macerated ginger root, fresh local honey, sparkling water, and cold-pressed lime.', 34, 'mocktail', ARRAY['Organic Ginger Root', 'Wildflower Honey', 'Carbonated Spring Water', 'Key Lime'], 85, 'A sharp, cleansing ginger burn soothed by sweet honey undertones.', false),
('k-3', 'Spiced Grove', 'Seedlip Spice 94 blend, organic apple reduction, cloves, star anise, and a splash of tonic.', 36, 'mocktail', ARRAY['Seedlip Spice 94', 'Organic Red Apple Juice', 'Clove & Star Anise Infusion', 'Light Tonic'], 70, 'Deeply aromatic winter spices paired with dry, woodsy bark elements.', false);
